### ISSUE TITLE
Error: Could not find or load main class com.theaigames.blockbattle.Blockbattle

### ISSUE THREAD

**Issue by jordao76** [theaigames/fourinarow-engine#1]
Hello, following the instructions in the README and running a battle results in:

Error: Could not find or load main class com.theaigames.blockbattle.Blockbattle

Note that I couldn't find the class com.theaigames.blockbattle.Blockbattle in the src tree.

**Comment by jordao76** [comment]
In fact, I noticed that the main method is in class com.theaigames.fourinarow.FourInARow. This should be added to the readme file.

**Comment by JimVanEeden** [comment]
Sorry that was a mistake in the readme, I'm fixing it.

**Comment by jordao76** [comment]
This was fixed, so I'm closing the issue.
